from typing import Protocol, Iterable, Mapping, Any, Optional, Dict
from datetime import date

class Client(Protocol):
    ''' authentication client '''
    async def authenticate(self, email: str, password: str) -> None: ...
    async def submit_mfa_code(self, mfa_code: str) -> bool: ...

class DB(Protocol):
    ''' database client '''
    async def upsert_raw_sessions(self, rows: Iterable[Mapping[str, Any]]) -> int: ...
    async def upsert_raw_laps(self, rows: Iterable[Mapping[str, Any]]) -> int: ...
    async def upsert_raw_intervals(self, rows: Iterable[Mapping[str, Any]]) -> int: ...

class APIRepository(Protocol):
    ''' api repository '''
    # Core activity data
    async def list_activities(self, day: date) -> list[dict]: ...
    async def get_activity_details(self, activity_id: int) -> dict: ...
    
    # Core health/recovery data
    async def get_recovery_data(self, day: date) -> dict: ...
    async def get_recovery_metric_details(self, metric_id: str) -> dict: ...

class Cache(Protocol):
    ''' cache manager '''
    async def load_from_cache(self, target_date: date) -> Optional[Dict[str, Any]]: ...
    async def save_to_cache(self, target_date: date, data: Dict[str, Any]) -> None: ...

class NotificationService(Protocol):
    ''' notification service '''
    async def notify_job_event(self, event_type: str, job_id: str, message: str, **kwargs) -> None: ...
    async def notify_batch_event(self, event_type: str, job_ids: list[str], message: str, **kwargs) -> None: ...
    async def notify_system_event(self, event_type: str, message: str, **kwargs) -> None: ...

